import { createContext, useContext, useState, useEffect } from 'react'
import PropTypes from 'prop-types'

const translations = {
  es: {
    // Navbar
    nav: {
      home: 'Inicio',
      forums: 'Foros',
      trivia: 'Trivia',
      map: 'Mi Mapa',
      profile: 'Perfil',
      login: 'Entrar',
      register: 'Registrarse',
      logout: 'Salir',
      createForum: 'Crear Foro',
      myProfile: 'Mi Perfil',
    },
    // Home
    home: {
      welcome: '¡Bienvenido a ForumViajeros!',
      subtitle: 'La comunidad de viajeros más grande',
      demo: 'VERSIÓN DEMO',
      adventureAwaits: 'LA AVENTURA TE ESPERA...',
      exploreUnknown: 'EXPLORA LO DESCONOCIDO...',
      timeToTravel: 'ES HORA DE VIAJAR...',
      discoverWorlds: 'DESCUBRE NUEVOS MUNDOS...',
      journeyStarts: 'TU VIAJE COMIENZA AQUÍ...',
      exploreForum: 'Explorar Foros',
      playTrivia: 'Jugar Trivia',
      myMap: 'Mi Mapa',
      adventure: 'Aventura',
      jungle: 'Jungla',
      profile: 'Perfil',
      trivia: 'Trivia',
      latestAdventures: 'Últimas Aventuras',
      loading: 'Cargando...',
      explore: 'Explorar',
      noForums: 'No hay foros disponibles',
      viewAllForums: 'Ver Todos los Foros',
      continents: 'Continentes',
      joinNow: 'Únete Ahora',
      featuredForums: 'Foros Destacados',
      recentPosts: 'Publicaciones Recientes',
    },
    // Auth
    auth: {
      loginTitle: 'Iniciar Sesión',
      registerTitle: 'Crear Cuenta',
      username: 'Usuario',
      usernamePlaceholder: 'Nombre de usuario',
      email: 'Correo Electrónico',
      emailPlaceholder: 'tu@email.com',
      password: 'Contraseña',
      passwordPlaceholder: 'Mínimo 6 caracteres',
      passwordLoginPlaceholder: 'Ingresa tu contraseña',
      confirmPassword: 'Confirmar Contraseña',
      forgotPassword: '¿Olvidaste tu contraseña?',
      noAccount: '¿No tienes cuenta?',
      hasAccount: '¿Ya tienes cuenta?',
      loginButton: 'Entrar',
      registerButton: 'Registrarse',
      loginSuccess: '¡Bienvenido de nuevo!',
      registerSuccess: '¡Cuenta creada exitosamente!',
      loginError: 'Usuario o contraseña incorrectos',
    },
    // Forums
    forums: {
      title: 'Foros de Viajeros',
      subtitle: 'Explora experiencias de viajeros',
      createNew: 'Crear Nuevo Foro',
      categories: 'Categorías',
      recentTopics: 'Temas Recientes',
      noForums: 'No hay foros disponibles',
      noPosts: 'Aún no hay publicaciones en este foro',
      beFirst: 'Sé el Primero',
      posts: 'Publicaciones',
      newPost: 'Nueva Publicación',
      rules: 'Reglas del Foro',
      loadingAdventure: 'Cargando Aventura...',
      replies: 'respuestas',
      views: 'vistas',
      backToForums: 'Volver a los foros',
      tipsTitle: 'Consejos para crear un buen foro',
      tipDescriptiveTitle: 'Título descriptivo:',
      tipDescriptiveTitleText: 'Usa un título claro que indique el tema o destino',
      tipFullDescription: 'Descripción completa:',
      tipFullDescriptionText: 'Explica de qué tratará el foro y qué tipo de contenido se compartirá',
      tipAppropriateCategory: 'Categoría apropiada:',
      tipAppropriateCategoryText: 'Selecciona la categoría que mejor represente el tema',
      tipBeSpecific: 'Sé específico:',
      tipBeSpecificText: 'Los foros específicos generan mejores discusiones que los muy generales',
      editForum: 'Editar foro',
      createDescription: 'Crea un espacio para compartir experiencias sobre un destino o tema de viaje',
      formTitle: 'Título',
      formDescription: 'Descripción',
      formContinent: 'Continente',
      formImage: 'Imagen',
      formTitlePlaceholder: 'Título del foro',
      formDescriptionPlaceholder: 'Descripción del foro',
      imageLoaded: 'Imagen cargada',
      noImageSelected: 'No se ha seleccionado ninguna imagen',
      createButton: 'Crear Foro',
      updateButton: 'Actualizar Foro',
      creating: 'Creando...',
      updating: 'Actualizando...',
      cancel: 'Cancelar',
      errorLoadingCategories: 'No se pudieron cargar las categorías',
      errorLoadingPosts: 'No se pudieron cargar las publicaciones',
      deleteImage: 'Eliminar imagen',
      tryAgain: 'Por favor, inténtalo de nuevo',
      imageTooLarge: 'La imagen debe ser menor a 5 MB',
      invalidImageFormat: 'El formato de imagen debe ser JPEG, PNG, GIF o WEBP',
      selectContinent: 'Selecciona un continente',
      selectImage: 'Seleccionar imagen',
      imageOptional: 'Imagen (opcional)',
      required: '*',
      noPermissionEdit: 'No tienes permiso para editar este foro',
      errorLoadingForum: 'No se pudo cargar el foro',
      redirecting: 'Serás redirigido en unos segundos...',
      forumNotFound: 'Foro no encontrado',
      backToForum: 'Volver al foro',
      updateForumInfo: 'Actualiza la información de tu foro',
      errorDeletingForum: 'No se pudo eliminar el foro',
      confirmDeleteForum: '¿Estás seguro de que quieres eliminar este foro? Esta acción no se puede deshacer.',
      forumDeletedSuccess: 'Foro eliminado con éxito',
    },
    // Trivia
    trivia: {
      title: 'Trivia Geográfica',
      startGame: 'Iniciar Juego',
      quickGame: 'Partida Rápida',
      infiniteMode: 'Modo Infinito',
      leaderboard: 'Clasificación',
      score: 'Puntuación',
      correct: '¡Correcto!',
      incorrect: 'Incorrecto',
      nextQuestion: 'Siguiente Pregunta',
      chooseMode: 'Elige un modo',
      questions: 'preguntas',
      randomQuestions: 'preguntas aleatorias',
      challengingQuestions: 'preguntas desafiantes',
      unlimitedQuestions: 'Preguntas ilimitadas',
      dailySpecial: 'Trivia diaria especial',
      playByContinent: 'Jugar por continente',
      ranking: 'Ranking',
      competeWithOthers: 'Compite con otros',
      myMap: 'Mi Mapa',
      registerTrips: 'Registra viajes',
      join: 'Únete',
      loginToSaveProgress: 'Inicia sesión para guardar progreso',
      tips: {
        title: 'Consejos',
        speedBonus: 'Responde rápido para puntos extra',
        keepStreak: 'Mantén tu racha activa',
        playDaily: 'Juega la trivia diaria',
        perfectGames: 'Partidas perfectas suben nivel',
      },
      abandon: 'Abandonar',
      correctAnswers: 'Correctas',
      loadingQuestion: 'Cargando pregunta...',
      loading: 'Cargando...',
      question: 'Pregunta',
      of: 'de',
      points: 'pts',
      level: 'Nivel',
      quickMode: 'Rápida',
      challengeMode: 'Desafío',
      dailyMode: 'Diaria',
      spaceMode: 'SPACE MODE',
      login: 'LOGIN',
      rank: 'Rango',
      bestStreak: 'Mejor racha',
      globalRanking: 'Ranking Global',
      precision: 'Precisión',
      streaks: 'Rachas',
      loadingRanking: 'Cargando ranking...',
      noPlayersYet: 'Aún no hay jugadores',
      you: 'Tú',
      games: 'partidas',
      playersInRanking: 'jugadores en el ranking',
      infinite: {
        loadingQuestions: 'Cargando preguntas desde API...',
        generatingTrivia: 'Generando trivia con datos reales de países',
        gameOver: '¡Fin del Juego!',
        infiniteMode: 'Modo Trivia Infinita',
        scoreLabel: 'Puntuación',
        bestStreakLabel: 'Mejor racha',
        questionsLabel: 'Preguntas',
        precisionLabel: 'Precisión',
        playAgain: 'Jugar de nuevo',
        backToMenu: 'Volver al menú',
        scoreText: 'PUNTUACIÓN',
        streakText: 'RACHA',
        lives: 'Vidas',
        exit: 'Salir',
        nextQuestion: 'Siguiente pregunta',
        loadingMore: 'Cargando más preguntas...',
        modeInfo: 'Modo Infinito • Preguntas generadas con RestCountries API',
        uniqueQuestions: 'preguntas únicas jugadas',
        errorLoadingQuestions: 'Error al cargar preguntas',
        noMoreQuestions: 'No hay más preguntas disponibles',
        gameOverNoLives: '¡Game Over! Sin vidas restantes',
        incorrectLives: 'Incorrecto. Vidas:',
        pointsEarned: 'puntos! 🔥 Racha:',
      },
      result: {
        correct: '¡Correcto!',
        incorrect: 'Incorrecto',
        correctAnswerWas: 'La respuesta correcta era:',
        pointsLabel: 'Puntos',
        streakLabel: 'Racha',
        funFact: '💡 Dato curioso:',
        viewResults: 'Ver resultados',
      },
      summary: {
        perfect: '¡Perfecto!',
        excellent: '¡Excelente!',
        veryGood: '¡Muy bien!',
        wellDone: '¡Bien hecho!',
        canImprove: 'Puedes mejorar',
        keepPracticing: 'Sigue practicando',
        perfectGame: '¡PARTIDA PERFECTA!',
        correct: 'Correctas',
        time: 'Tiempo',
        playAgainButton: 'Jugar otra vez',
        viewRanking: 'Ver ranking',
      },
    },
    // Travel Map
    travel: {
      title: 'Mi Mapa de Viajes',
      addPlace: 'Añadir Lugar',
      visitedCountries: 'Países Visitados',
      wishlist: 'Lista de Deseos',
      statistics: 'Estadísticas',
      percentWorld: '% del mundo visitado',
      editPlace: 'Editar Lugar',
      country: 'País',
      required: 'Obligatorio',
      cityOptional: 'Ciudad (Opcional)',
      status: 'Estado',
      visited: 'Visitado',
      wantToGo: 'Quiero Ir',
      lived: 'He Vivido',
      living: 'Vivo Aquí',
      visitDate: 'Fecha de Visita',
      visitDateOptional: 'Fecha de Visita (Opcional)',
      visitDateHelper: 'Puedes dejar este campo vacío si no recuerdas la fecha exacta',
      rating: 'Puntuación',
      notes: 'Notas',
      notesPlaceholder: '¿Qué te pareció? ¿Algún lugar especial?',
      markAsFavorite: 'Marcar como favorito',
      update: 'Actualizar',
      add: 'Agregar',
      saving: 'Guardando...',
      selectCountry: 'Por favor, selecciona un país',
      placeAdded: 'agregado a tu mapa!',
      placeUpdated: 'Lugar actualizado exitosamente',
      errorSaving: 'Error al guardar el lugar',
      remove: 'Quitar',
      addingPlace: 'Agregar Lugar',
      editingPlace: 'Editar Lugar',
      modifyDetails: 'Modifica los detalles',
      addNewDestination: 'Añade un nuevo destino',
    },
    // Posts
    posts: {
      newPost: 'Nueva Publicación',
      shareExperience: 'Comparte tu experiencia, pregunta o información en el foro',
      loadError: 'No se pudo cargar el foro',
      forumNotFound: 'Foro no encontrado',
      viewForums: 'Ver foros disponibles',
    },
    // Common
    common: {
      loading: 'Cargando...',
      error: 'Ha ocurrido un error',
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      search: 'Buscar',
      filter: 'Filtrar',
      sortBy: 'Ordenar por',
      showMore: 'Ver más',
      showLess: 'Ver menos',
      back: 'Volver',
      backToForum: 'Volver al foro',
      next: 'Siguiente',
      previous: 'Anterior',
      optional: 'Opcional',
      close: 'Cerrar',
      readMore: 'Leer Más',
      comment: 'comentario',
      comments: 'comentarios',
      view: 'vista',
      views: 'vistas',
      post: 'publicación',
      posts: 'publicaciones',
      user: 'usuario',
    },
    // Footer
    footer: {
      about: 'Sobre Nosotros',
      contact: 'Contacto',
      privacy: 'Privacidad',
      terms: 'Términos',
      rights: 'Todos los derechos reservados',
    },
    // Profile
    profile: {
      title: 'Perfil',
      loading: 'Cargando perfil...',
      mustLogin: 'Debes iniciar sesión',
      personalInfo: 'Información Personal',
      profileImage: 'Imagen de Perfil',
      changeImage: 'Cambiar Imagen',
      firstName: 'Nombre',
      lastName: 'Apellido',
      bio: 'Biografía',
      bioPlaceholder: 'Cuéntanos sobre ti...',
      password: 'Contraseña',
      currentPassword: 'Contraseña Actual',
      newPassword: 'Nueva Contraseña',
      confirmPassword: 'Confirmar Contraseña',
      updateProfile: 'Actualizar Perfil',
      updatePassword: 'Actualizar Contraseña',
      updating: 'Actualizando...',
      profileUpdated: 'Perfil actualizado correctamente',
      passwordUpdated: 'Contraseña actualizada correctamente',
      forums: 'Foros',
      posts: 'Publicaciones',
      myForums: 'Mis Foros',
      noForums: 'Aún no has creado ningún foro',
      createForum: 'Crear Foro',
      myPosts: 'Mis Publicaciones',
      noPosts: 'Aún no has publicado nada',
      tabs: {
        profile: 'Perfil',
        password: 'Contraseña',
        forums: 'Foros',
        posts: 'Publicaciones',
      },
    }
  },
  en: {
    // Navbar
    nav: {
      home: 'Home',
      forums: 'Forums',
      trivia: 'Trivia',
      map: 'My Map',
      profile: 'Profile',
      login: 'Login',
      register: 'Sign Up',
      logout: 'Logout',
      createForum: 'Create Forum',
      myProfile: 'My Profile',
    },
    // Home
    home: {
      welcome: 'Welcome to ForumViajeros!',
      subtitle: 'The largest travelers community',
      demo: 'DEMO VERSION',
      adventureAwaits: 'ADVENTURE AWAITS...',
      exploreUnknown: 'EXPLORE THE UNKNOWN...',
      timeToTravel: 'TIME TO TRAVEL...',
      discoverWorlds: 'DISCOVER NEW WORLDS...',
      journeyStarts: 'YOUR JOURNEY STARTS HERE...',
      exploreForum: 'Explore Forums',
      playTrivia: 'Play Trivia',
      myMap: 'My Map',
      adventure: 'Adventure',
      jungle: 'Jungle',
      profile: 'Profile',
      trivia: 'Trivia',
      latestAdventures: 'Latest Adventures',
      loading: 'Loading...',
      explore: 'Explore',
      noForums: 'No forums available',
      viewAllForums: 'View All Forums',
      continents: 'Continents',
      joinNow: 'Join Now',
      featuredForums: 'Featured Forums',
      recentPosts: 'Recent Posts',
    },
    // Auth
    auth: {
      loginTitle: 'Login',
      registerTitle: 'Create Account',
      username: 'Username',
      usernamePlaceholder: 'Username',
      email: 'Email',
      emailPlaceholder: 'you@email.com',
      password: 'Password',
      passwordPlaceholder: 'Minimum 6 characters',
      passwordLoginPlaceholder: 'Enter your password',
      confirmPassword: 'Confirm Password',
      forgotPassword: 'Forgot your password?',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      loginButton: 'Login',
      registerButton: 'Sign Up',
      loginSuccess: 'Welcome back!',
      registerSuccess: 'Account created successfully!',
      loginError: 'Invalid username or password',
    },
    // Forums
    forums: {
      title: 'Travelers Forums',
      subtitle: 'Explore travelers experiences',
      createNew: 'Create New Forum',
      categories: 'Categories',
      recentTopics: 'Recent Topics',
      noForums: 'No forums available',
      noPosts: 'No posts yet in this forum',
      beFirst: 'Be the First',
      posts: 'Posts',
      newPost: 'New Post',
      rules: 'Forum Rules',
      loadingAdventure: 'Loading Adventure...',
      replies: 'replies',
      views: 'views',
      backToForums: 'Back to forums',
      tipsTitle: 'Tips for creating a good forum',
      tipDescriptiveTitle: 'Descriptive title:',
      tipDescriptiveTitleText: 'Use a clear title that indicates the topic or destination',
      tipFullDescription: 'Full description:',
      tipFullDescriptionText: 'Explain what the forum will be about and what kind of content will be shared',
      tipAppropriateCategory: 'Appropriate category:',
      tipAppropriateCategoryText: 'Select the category that best represents the topic',
      tipBeSpecific: 'Be specific:',
      tipBeSpecificText: 'Specific forums generate better discussions than very general ones',
      editForum: 'Edit forum',
      createDescription: 'Create a space to share experiences about a destination or travel topic',
      formTitle: 'Title',
      formDescription: 'Description',
      formContinent: 'Continent',
      formImage: 'Image',
      formTitlePlaceholder: 'Forum title',
      formDescriptionPlaceholder: 'Forum description',
      imageLoaded: 'Image loaded',
      noImageSelected: 'No image selected',
      createButton: 'Create Forum',
      updateButton: 'Update Forum',
      creating: 'Creating...',
      updating: 'Updating...',
      cancel: 'Cancel',
      errorLoadingCategories: 'Could not load categories',
      errorLoadingPosts: 'Could not load posts',
      deleteImage: 'Delete image',
      tryAgain: 'Please try again',
      imageTooLarge: 'Image must be smaller than 5 MB',
      invalidImageFormat: 'Image format must be JPEG, PNG, GIF or WEBP',
      selectContinent: 'Select a continent',
      selectImage: 'Select image',
      imageOptional: 'Image (optional)',
      required: '*',
      noPermissionEdit: 'You do not have permission to edit this forum',
      errorLoadingForum: 'Could not load forum',
      redirecting: 'You will be redirected in a few seconds...',
      forumNotFound: 'Forum not found',
      backToForum: 'Back to forum',
      updateForumInfo: 'Update your forum information',
      errorDeletingForum: 'Could not delete forum',
      confirmDeleteForum: 'Are you sure you want to delete this forum? This action cannot be undone.',
      forumDeletedSuccess: 'Forum deleted successfully',
    },
    // Trivia
    trivia: {
      title: 'Geographic Trivia',
      startGame: 'Start Game',
      quickGame: 'Quick Game',
      infiniteMode: 'Infinite Mode',
      leaderboard: 'Leaderboard',
      score: 'Score',
      correct: 'Correct!',
      incorrect: 'Incorrect',
      nextQuestion: 'Next Question',
      chooseMode: 'Choose a mode',
      questions: 'questions',
      randomQuestions: 'random questions',
      challengingQuestions: 'challenging questions',
      unlimitedQuestions: 'Unlimited questions',
      dailySpecial: 'Daily special trivia',
      playByContinent: 'Play by continent',
      ranking: 'Ranking',
      competeWithOthers: 'Compete with others',
      myMap: 'My Map',
      registerTrips: 'Register trips',
      join: 'Join',
      loginToSaveProgress: 'Login to save progress',
      tips: {
        title: 'Tips',
        speedBonus: 'Answer quickly for extra points',
        keepStreak: 'Keep your streak active',
        playDaily: 'Play the daily trivia',
        perfectGames: 'Perfect games level up',
      },
      abandon: 'Abandon',
      correctAnswers: 'Correct',
      loadingQuestion: 'Loading question...',
      loading: 'Loading...',
      question: 'Question',
      of: 'of',
      points: 'pts',
      level: 'Level',
      quickMode: 'Quick',
      challengeMode: 'Challenge',
      dailyMode: 'Daily',
      spaceMode: 'SPACE MODE',
      login: 'LOGIN',
      rank: 'Rank',
      bestStreak: 'Best streak',
      globalRanking: 'Global Ranking',
      precision: 'Precision',
      streaks: 'Streaks',
      loadingRanking: 'Loading ranking...',
      noPlayersYet: 'No players yet',
      you: 'You',
      games: 'games',
      playersInRanking: 'players in the ranking',
      infinite: {
        loadingQuestions: 'Loading questions from API...',
        generatingTrivia: 'Generating trivia with real country data',
        gameOver: 'Game Over!',
        infiniteMode: 'Infinite Trivia Mode',
        scoreLabel: 'Score',
        bestStreakLabel: 'Best streak',
        questionsLabel: 'Questions',
        precisionLabel: 'Precision',
        playAgain: 'Play again',
        backToMenu: 'Back to menu',
        scoreText: 'SCORE',
        streakText: 'STREAK',
        lives: 'Lives',
        exit: 'Exit',
        nextQuestion: 'Next question',
        loadingMore: 'Loading more questions...',
        modeInfo: 'Infinite Mode • Questions generated with RestCountries API',
        uniqueQuestions: 'unique questions played',
        errorLoadingQuestions: 'Error loading questions',
        noMoreQuestions: 'No more questions available',
        gameOverNoLives: 'Game Over! No lives remaining',
        incorrectLives: 'Incorrect. Lives:',
        pointsEarned: 'points! 🔥 Streak:',
      },
      result: {
        correct: 'Correct!',
        incorrect: 'Incorrect',
        correctAnswerWas: 'The correct answer was:',
        pointsLabel: 'Points',
        streakLabel: 'Streak',
        funFact: '💡 Fun fact:',
        viewResults: 'View results',
      },
      summary: {
        perfect: 'Perfect!',
        excellent: 'Excellent!',
        veryGood: 'Very good!',
        wellDone: 'Well done!',
        canImprove: 'You can improve',
        keepPracticing: 'Keep practicing',
        perfectGame: 'PERFECT GAME!',
        correct: 'Correct',
        time: 'Time',
        playAgainButton: 'Play again',
        viewRanking: 'View ranking',
      },
    },
    // Travel Map
    travel: {
      title: 'My Travel Map',
      addPlace: 'Add Place',
      visitedCountries: 'Visited Countries',
      wishlist: 'Wishlist',
      statistics: 'Statistics',
      percentWorld: '% of world visited',
      editPlace: 'Edit Place',
      country: 'Country',
      required: 'Required',
      cityOptional: 'City (Optional)',
      status: 'Status',
      visited: 'Visited',
      wantToGo: 'Want to Go',
      lived: 'Have Lived',
      living: 'Living Here',
      visitDate: 'Visit Date',
      visitDateOptional: 'Visit Date (Optional)',
      visitDateHelper: 'You can leave this field empty if you don\'t remember the exact date',
      rating: 'Rating',
      notes: 'Notes',
      notesPlaceholder: 'What did you think? Any special place?',
      markAsFavorite: 'Mark as favorite',
      update: 'Update',
      add: 'Add',
      saving: 'Saving...',
      selectCountry: 'Please, select a country',
      placeAdded: 'added to your map!',
      placeUpdated: 'Place updated successfully',
      errorSaving: 'Error saving the place',
      remove: 'Remove',
      addingPlace: 'Add Place',
      editingPlace: 'Edit Place',
      modifyDetails: 'Modify the details',
      addNewDestination: 'Add a new destination',
    },
    // Posts
    posts: {
      newPost: 'New Post',
      shareExperience: 'Share your experience, question or information in the forum',
      loadError: 'Could not load forum',
      forumNotFound: 'Forum not found',
      viewForums: 'View available forums',
    },
    // Common
    common: {
      loading: 'Loading...',
      error: 'An error occurred',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      search: 'Search',
      filter: 'Filter',
      sortBy: 'Sort by',
      showMore: 'Show more',
      showLess: 'Show less',
      back: 'Back',
      backToForum: 'Back to forum',
      next: 'Next',
      previous: 'Previous',
      optional: 'Optional',
      close: 'Close',
      readMore: 'Read More',
      comment: 'comment',
      comments: 'comments',
      view: 'view',
      views: 'views',
      post: 'post',
      posts: 'posts',
      user: 'user',
    },
    // Footer
    footer: {
      about: 'About Us',
      contact: 'Contact',
      privacy: 'Privacy',
      terms: 'Terms',
      rights: 'All rights reserved',
    },
    // Profile
    profile: {
      title: 'Profile',
      loading: 'Loading profile...',
      mustLogin: 'You must log in',
      personalInfo: 'Personal Information',
      profileImage: 'Profile Image',
      changeImage: 'Change Image',
      firstName: 'First Name',
      lastName: 'Last Name',
      bio: 'Bio',
      bioPlaceholder: 'Tell us about yourself...',
      password: 'Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      updateProfile: 'Update Profile',
      updatePassword: 'Update Password',
      updating: 'Updating...',
      profileUpdated: 'Profile updated successfully',
      passwordUpdated: 'Password updated successfully',
      forums: 'Forums',
      posts: 'Posts',
      myForums: 'My Forums',
      noForums: 'You haven\'t created any forums yet',
      createForum: 'Create Forum',
      myPosts: 'My Posts',
      noPosts: 'You haven\'t posted anything yet',
      tabs: {
        profile: 'Profile',
        password: 'Password',
        forums: 'Forums',
        posts: 'Posts',
      },
    }
  }
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language')
    return saved || 'es'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
    document.documentElement.lang = language
  }, [language])

  const t = (key) => {
    const keys = key.split('.')
    let value = translations[language]
    
    for (const k of keys) {
      if (value && value[k]) {
        value = value[k]
      } else {
        // Fallback amigable para claves frecuentes usadas en tests
        const fallbacks = {
          'common.posts': 'publicaciones',
          'common.comments': 'comentarios',
          'common.views': 'vistas',
          'common.readMore': 'Leer Más',
          // Home keys
          'home.exploreForum': 'Explorar foros',
          'home.trivia': 'Jugar trivia',
          'home.myMap': 'Mi mapa',
          'home.adventureAwaits': 'La aventura te espera',
          'home.demo': 'Descubre, comparte y explora',
          'home.noForums': 'No hay foros disponibles',
          'auth.username': 'Usuario',
          'auth.usernamePlaceholder': 'Nombre de usuario',
          'auth.email': 'Correo Electrónico',
          'auth.emailPlaceholder': 'tu@email.com',
          'auth.password': 'Contraseña',
          'auth.passwordPlaceholder': 'Mínimo 6 caracteres',
          'auth.passwordLoginPlaceholder': 'Ingresa tu contraseña',
          'auth.confirmPassword': 'Confirmar Contraseña',
          'auth.registerButton': 'Registrarse',
          'auth.loginButton': 'Acceder',
          'common.registering': 'Registrando...',
        }
        return fallbacks[key] || key
      }
    }
    
    return value
  }

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es')
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

LanguageProvider.propTypes = {
  children: PropTypes.node.isRequired
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    // Fallback seguro en entorno de pruebas cuando no hay Provider
    return {
      language: 'es',
      setLanguage: () => {},
      toggleLanguage: () => {},
      t: (key) => {
        const fallbacks = {
          'common.posts': 'publicaciones',
          'common.comments': 'comentarios',
          'common.views': 'vistas',
          'common.readMore': 'Leer Más',
          // Home keys
          'home.exploreForum': 'Explorar foros',
          'home.trivia': 'Jugar trivia',
          'home.myMap': 'Mi mapa',
          'home.adventureAwaits': 'La aventura te espera',
          'home.demo': 'Descubre, comparte y explora',
          'home.noForums': 'No hay foros disponibles',
          'auth.username': 'Usuario',
          'auth.usernamePlaceholder': 'Nombre de usuario',
          'auth.email': 'Correo Electrónico',
          'auth.emailPlaceholder': 'tu@email.com',
          'auth.password': 'Contraseña',
          'auth.passwordPlaceholder': 'Mínimo 6 caracteres',
          'auth.passwordLoginPlaceholder': 'Ingresa tu contraseña',
          'auth.confirmPassword': 'Confirmar Contraseña',
          'auth.registerButton': 'Registrarse',
          'auth.loginButton': 'Acceder',
          'common.registering': 'Registrando...',
        }
        return fallbacks[key] || key
      },
    }
  }
  return context
}

export default LanguageContext

